import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f8fafc',
  '--slot4-page-text': '#0c1117',
  '--slot4-panel-bg': '#f1f5f9',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#64748b',
  '--slot4-soft-muted-text': '#94a3b8',
  '--slot4-accent': '#f97316',
  '--slot4-accent-fill': '#f97316',
  '--slot4-accent-soft': '#fff7ed',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#0c1117',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e2e8f0',
  '--slot4-cream': '#fffbf5',
  '--slot4-warm': '#f8fafc',
  '--slot4-lavender': '#f1f5f9',
  '--slot4-gray': '#f1f5f9',
  '--slot4-primary': '#06b6d4',
  '--slot4-secondary': '#f59e0b',
  '--slot4-tertiary': '#ec4899',
  '--slot4-green': '#10b981',
  '--slot4-body-gradient': 'linear-gradient(135deg,#f8fafc 0%,#f1f5f9 100%)',
  '--editable-page-bg': '#f8fafc',
  '--editable-page-text': '#0c1117',
  '--editable-container': '1280px',
  '--editable-border': '#e2e8f0',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#0c1117',
  '--editable-nav-active': '#f97316',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#f97316',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#0c1117',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_4px_rgba(0,0,0,0.06)]',
  shadowMd: 'shadow-[0_4px_16px_rgba(0,0,0,0.08)]',
  shadowStrong: 'shadow-[0_8px_32px_rgba(0,0,0,0.12)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.01),rgba(0,0,0,0.70))]',
} as const

export const editableDesignContract = {
  shell: {
    page: 'min-h-screen bg-[var(--slot4-page-bg)] text-[var(--slot4-page-text)]',
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[160px] shrink-0 snap-start sm:w-[180px]',
  },
  type: {
    eyebrow: 'text-xs font-bold uppercase tracking-[0.2em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-extrabold leading-[1.1] tracking-[-0.02em] sm:text-5xl lg:text-[3.5rem]',
    sectionTitle: 'text-2xl font-bold tracking-[-0.01em] sm:text-3xl',
    body: 'text-base leading-relaxed text-[var(--slot4-muted-text)]',
  },
  surface: {
    card: 'rounded-2xl border border-[var(--editable-border)] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.06)]',
    soft: 'rounded-2xl border border-[var(--editable-border)] bg-[var(--slot4-panel-bg)]',
    dark: 'rounded-2xl bg-[var(--slot4-dark-bg)] text-white shadow-[0_8px_32px_rgba(0,0,0,0.2)]',
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--slot4-accent)] px-6 py-3 text-sm font-bold text-white shadow-[0_2px_8px_rgba(249,115,22,0.35)] transition hover:brightness-105 hover:-translate-y-0.5 active:scale-[0.98]',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--editable-border)] bg-white px-6 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]',
    ghost: 'inline-flex items-center justify-center gap-2 rounded-xl px-6 py-3 text-sm font-semibold text-[var(--slot4-muted-text)] transition hover:bg-[var(--slot4-panel-bg)] hover:text-[var(--slot4-page-text)]',
  },
  media: {
    frame: 'relative overflow-hidden rounded-2xl bg-[var(--slot4-media-bg)]',
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_12px_32px_rgba(0,0,0,0.12)]',
    fade: 'transition duration-300 hover:opacity-80',
    scale: 'transition duration-500 group-hover:scale-105',
  },
} as const

export const aiLayoutRules = [] as const
